import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.gradle.ktlint)
    alias(libs.plugins.vanniktechMavenPublish)
}

android {
    namespace = "dev.rikkaui.foundation"
    compileSdk = 35
    defaultConfig {
        minSdk = 24
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

kotlin {
    androidTarget {
        publishLibraryVariants("release")
    }

    jvm("desktop")

    iosX64()
    iosArm64()
    iosSimulatorArm64()

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }
    js {
        browser()
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.ui)
                implementation(libs.compose.components.resources)
            }
        }
    }
}

// ─── Generate RikkaVersion.kt from gradle.properties ───────
val generateVersion by tasks.registering {
    val versionName = project.property("VERSION_NAME") as String
    val groupId = project.property("GROUP") as String
    val outputDir = layout.buildDirectory.dir("generated/version/kotlin")

    inputs.property("versionName", versionName)
    outputs.dir(outputDir)

    doLast {
        val dir = outputDir.get().asFile.resolve(
            "zed/rainxch/rikkaui/foundation",
        )
        dir.mkdirs()
        dir.resolve("RikkaVersion.kt").writeText(
            """
            |// Generated by Gradle — do not edit.
            |package zed.rainxch.rikkaui.foundation
            |
            |/** Single source of truth for RikkaUI artifact versions. */
            |object RikkaVersion {
            |    const val NAME = "$versionName"
            |    const val FOUNDATION = "$groupId:foundation:$versionName"
            |    const val COMPONENTS = "$groupId:components:$versionName"
            |}
            """.trimMargin(),
        )
    }
}

kotlin.sourceSets.commonMain {
    kotlin.srcDir(generateVersion.map { it.outputs.files.singleFile })
}

ktlint {
    ignoreFailures = true
}

signing {
    useInMemoryPgpKeys(
        findProperty("signingInMemoryKeyId") as String?,
        findProperty("signingInMemoryKey") as String?,
        findProperty("signingInMemoryKeyPassword") as String?,
    )
}

mavenPublishing {
    pom {
        name = "RikkaUI Foundation"
        description = "Theme tokens and design system foundation for Compose Multiplatform"
    }
}
