package zed.rainxch.rikkaui.creator.codegen

import zed.rainxch.rikkaui.foundation.RikkaAccentPreset
import zed.rainxch.rikkaui.foundation.RikkaPalette
import zed.rainxch.rikkaui.foundation.RikkaStylePreset

/** The base package for the `:foundation` module. */
private const val FOUNDATION_PKG = "zed.rainxch.rikkaui.foundation"

/**
 * Generates Kotlin source code for a user's configured design system.
 *
 * The generated `AppTheme.kt` file contains:
 * - Color resolution (palette + accent)
 * - Typography wiring with the selected font
 * - A ready-to-use `AppTheme` composable wrapping [RikkaTheme]
 *
 * All imports reference `rikkaui:foundation` — the theme-only module.
 */
fun generateThemeCode(
    palette: RikkaPalette,
    accent: RikkaAccentPreset,
    stylePreset: RikkaStylePreset,
    fontId: String,
    fontDisplayName: String,
): String {
    val fontResourceNames = buildFontResourceNames(fontId)

    return buildString {
        appendLine("package com.example.app.theme")
        appendLine()
        appendLine("import androidx.compose.runtime.Composable")
        appendLine("import $FOUNDATION_PKG.RikkaPalette")
        appendLine("import $FOUNDATION_PKG.RikkaAccentPreset")
        appendLine("import $FOUNDATION_PKG.RikkaStylePreset")
        appendLine("import $FOUNDATION_PKG.RikkaTheme")
        appendLine("import $FOUNDATION_PKG.rikkaTypography")
        appendLine("import $FOUNDATION_PKG.rememberRikkaFontFamily")
        appendLine()
        appendLine("/**")
        appendLine(
            " * App theme generated by RikkaUI" +
                " Design System Creator.",
        )
        appendLine(" *")
        appendLine(" * Palette: ${palette.label}")
        appendLine(" * Accent: ${accent.label}")
        appendLine(" * Style: ${stylePreset.label}")
        appendLine(" * Font: $fontDisplayName")
        appendLine(" */")
        appendLine("@Composable")
        appendLine("fun AppTheme(")
        appendLine("    isDark: Boolean = true,")
        appendLine("    content: @Composable () -> Unit,")
        appendLine(") {")
        appendLine("    val fontFamily = rememberRikkaFontFamily(")
        appendLine(
            "        regular = " +
                "Res.font.${fontResourceNames.first},",
        )
        appendLine(
            "        bold = " +
                "Res.font.${fontResourceNames.second},",
        )
        appendLine("    )")
        appendLine()
        appendLine("    RikkaTheme(")
        appendLine(
            "        palette = RikkaPalette.${palette.name},",
        )
        appendLine(
            "        accent = RikkaAccentPreset.${accent.name},",
        )
        appendLine("        isDark = isDark,")
        appendLine(
            "        preset = RikkaStylePreset.${stylePreset.name},",
        )
        appendLine(
            "        typography = rikkaTypography(" +
                "fontFamily, scale = " +
                "RikkaStylePreset.${stylePreset.name}.typeScale),",
        )
        appendLine("        content = content,")
        appendLine("    )")
        appendLine("}")
    }
}

/** Generates a README.md with setup instructions. */
fun generateReadme(
    palette: RikkaPalette,
    accent: RikkaAccentPreset,
    stylePreset: RikkaStylePreset,
    fontDisplayName: String,
): String =
    buildString {
        appendLine("# Your RikkaUI Design System")
        appendLine()
        appendLine(
            "Generated by [RikkaUI](https://rikkaui.dev)" +
                " Design System Creator.",
        )
        appendLine()
        appendLine("## Configuration")
        appendLine()
        appendLine("| Setting | Value |")
        appendLine("|---------|-------|")
        appendLine("| Palette | ${palette.label} |")
        appendLine("| Accent  | ${accent.label} |")
        appendLine("| Style   | ${stylePreset.label} |")
        appendLine("| Font    | $fontDisplayName |")
        appendLine()
        appendLine("## Setup")
        appendLine()
        appendLine("### 1. Add RikkaUI dependencies")
        appendLine()
        appendLine(
            "Add these to your module's `build.gradle.kts`:",
        )
        appendLine()
        appendLine("```kotlin")
        appendLine("dependencies {")
        appendLine(
            "    // Theme system (required)" +
                " \u2014 provides RikkaTheme, colors," +
                " spacing, shapes, motion",
        )
        appendLine(
            "    implementation(" +
                "\"dev.rikkaui:foundation:0.1.0\")",
        )
        appendLine()
        appendLine(
            "    // UI components (optional)" +
                " \u2014 Button, Card, Input, Badge, etc.",
        )
        appendLine(
            "    implementation(" +
                "\"dev.rikkaui:components:0.1.0\")",
        )
        appendLine("}")
        appendLine("```")
        appendLine()
        appendLine(
            "> **`foundation`** is the only required dependency." +
                " It gives you the full",
        )
        appendLine(
            "> theming system. Add **`components`** when you" +
                " want pre-built UI widgets.",
        )
        appendLine()
        appendLine("### 2. Copy your theme files")
        appendLine()
        appendLine(
            "- Copy **`AppTheme.kt`** into your" +
                " project's theme package.",
        )
        appendLine(
            "- Copy the font files from **`font/`**" +
                " into your `composeResources/font/` directory.",
        )
        appendLine()
        appendLine("### 3. Wrap your app")
        appendLine()
        appendLine("```kotlin")
        appendLine("@Composable")
        appendLine("fun App() {")
        appendLine("    AppTheme(isDark = true) {")
        appendLine("        // Your content here")
        appendLine("    }")
        appendLine("}")
        appendLine("```")
        appendLine()
        appendLine("## What's in each dependency?")
        appendLine()
        appendLine(
            "| Module | Contains |",
        )
        appendLine("|--------|----------|")
        appendLine(
            "| `foundation` | RikkaTheme, RikkaColors," +
                " RikkaSpacing, RikkaShapes, RikkaMotion," +
                " RikkaTypography, style presets," +
                " color palettes, accent colors |",
        )
        appendLine(
            "| `components` | Button, Card, Input," +
                " Badge, Toggle, Checkbox, Dialog," +
                " Sheet, Tabs, Toast, Select," +
                " Accordion, Table, and 40+ more |",
        )
        appendLine()
        appendLine("## Customization")
        appendLine()
        appendLine(
            "You own this code! Modify `AppTheme.kt`" +
                " to adjust colors,",
        )
        appendLine(
            "spacing, shapes, or motion to match" +
                " your brand.",
        )
    }

private fun buildFontResourceNames(fontId: String): Pair<String, String> = Pair("${fontId}_regular", "${fontId}_bold")
