package zed.rainxch.rikkaui.creator

import zed.rainxch.rikkaui.components.theme.RikkaStylePreset

/**
 * Generates Kotlin source code for a user's configured design system.
 *
 * The generated `AppTheme.kt` file contains:
 * - Color resolution (palette + accent)
 * - Typography wiring with the selected font
 * - A ready-to-use `AppTheme` composable wrapping [RikkaTheme]
 */
fun generateThemeCode(
    paletteName: String,
    accentName: String,
    stylePreset: RikkaStylePreset,
    fontId: String,
    fontDisplayName: String,
): String {
    val fontResourceNames = buildFontResourceNames(fontId)
    val paletteImport = buildPaletteImport(paletteName)
    val accentImport = buildAccentImport(accentName)
    val accentApplication = buildAccentApplication(accentName)

    return buildString {
        appendLine("package com.example.app.theme")
        appendLine()
        appendLine("import androidx.compose.runtime.Composable")
        appendLine("import androidx.compose.runtime.getValue")
        appendLine("import androidx.compose.runtime.mutableStateOf")
        appendLine("import androidx.compose.runtime.remember")
        appendLine("import androidx.compose.runtime.setValue")
        appendLine("import androidx.compose.ui.text.font.FontFamily")
        appendLine("import androidx.compose.ui.text.font.FontWeight")
        appendLine("import org.jetbrains.compose.resources.Font")
        appendLine(
            "import zed.rainxch.rikkaui.components.theme" +
                ".RikkaStylePreset",
        )
        appendLine(
            "import zed.rainxch.rikkaui.components.theme.RikkaTheme",
        )
        appendLine(
            "import zed.rainxch.rikkaui.components.theme" +
                ".rikkaTypography",
        )
        appendLine(
            "import zed.rainxch.rikkaui.components.theme" +
                ".rememberRikkaFontFamily",
        )
        appendLine(paletteImport)
        if (accentImport.isNotEmpty()) appendLine(accentImport)
        appendLine()
        appendLine("/**")
        appendLine(
            " * App theme generated by RikkaUI Design System Creator.",
        )
        appendLine(" *")
        appendLine(" * Palette: $paletteName")
        appendLine(" * Accent: $accentName")
        appendLine(" * Style: ${stylePreset.label}")
        appendLine(" * Font: $fontDisplayName")
        appendLine(" */")
        appendLine("@Composable")
        appendLine("fun AppTheme(")
        appendLine("    isDark: Boolean = true,")
        appendLine("    content: @Composable () -> Unit,")
        appendLine(") {")
        appendLine("    val preset = RikkaStylePreset.${stylePreset.name}")
        appendLine()
        appendLine("    // ── Colors ──")
        appendLine(buildColorResolution(paletteName))
        appendLine(accentApplication)
        appendLine()
        appendLine("    // ── Typography ──")
        appendLine("    val fontFamily = rememberRikkaFontFamily(")
        appendLine(
            "        regular = Res.font.${fontResourceNames.first},",
        )
        appendLine(
            "        bold = Res.font.${fontResourceNames.second},",
        )
        appendLine("    )")
        appendLine()
        appendLine("    RikkaTheme(")
        appendLine("        colors = colors,")
        appendLine(
            "        typography = rikkaTypography(" +
                "fontFamily, scale = preset.typeScale),",
        )
        appendLine("        spacing = preset.spacing,")
        appendLine("        shapes = preset.shapes,")
        appendLine("        motion = preset.motion,")
        appendLine("        content = content,")
        appendLine("    )")
        appendLine("}")
    }
}

/** Generates a README.md with setup instructions. */
fun generateReadme(
    paletteName: String,
    accentName: String,
    stylePreset: RikkaStylePreset,
    fontDisplayName: String,
): String = buildString {
    appendLine("# Your RikkaUI Design System")
    appendLine()
    appendLine("Generated by [RikkaUI](https://rikkaui.dev)" +
        " Design System Creator.")
    appendLine()
    appendLine("## Configuration")
    appendLine()
    appendLine("| Setting | Value |")
    appendLine("|---------|-------|")
    appendLine("| Palette | $paletteName |")
    appendLine("| Accent  | $accentName |")
    appendLine("| Style   | ${stylePreset.label} |")
    appendLine("| Font    | $fontDisplayName |")
    appendLine()
    appendLine("## Setup")
    appendLine()
    appendLine("1. Add the RikkaUI components dependency:")
    appendLine()
    appendLine("```kotlin")
    appendLine("dependencies {")
    appendLine(
        "    implementation(\"zed.rainxch.rikkaui:components:1.0.0\")",
    )
    appendLine("}")
    appendLine("```")
    appendLine()
    appendLine("2. Copy `AppTheme.kt` into your project.")
    appendLine()
    appendLine(
        "3. Copy the font files from the `font/`" +
            " directory into your",
    )
    appendLine("   `composeResources/font/` directory.")
    appendLine()
    appendLine("4. Wrap your app content with `AppTheme`:")
    appendLine()
    appendLine("```kotlin")
    appendLine("@Composable")
    appendLine("fun App() {")
    appendLine("    AppTheme(isDark = true) {")
    appendLine("        // Your content here")
    appendLine("    }")
    appendLine("}")
    appendLine("```")
    appendLine()
    appendLine("## Customization")
    appendLine()
    appendLine(
        "You own this code! Modify `AppTheme.kt` to" +
            " adjust colors,",
    )
    appendLine(
        "spacing, shapes, or motion to match" +
            " your brand.",
    )
}

private fun buildFontResourceNames(fontId: String): Pair<String, String> =
    Pair("${fontId}_regular", "${fontId}_bold")

private fun buildPaletteImport(palette: String): String {
    val obj = "zed.rainxch.rikkaui.components.theme.RikkaPalettes"
    return "import $obj"
}

private fun buildAccentImport(accent: String): String {
    if (accent == "Default") return ""
    return "import zed.rainxch.rikkaui.components.theme.RikkaAccent\n" +
        "import zed.rainxch.rikkaui.components.theme.RikkaAccentDark\n" +
        "import zed.rainxch.rikkaui.components.theme.withAccent"
}

private fun buildColorResolution(palette: String): String {
    val lightVal = "${palette}Light"
    val darkVal = "${palette}Dark"
    return "    val baseColors = if (isDark) " +
        "RikkaPalettes.$darkVal else RikkaPalettes.$lightVal"
}

private fun buildAccentApplication(accent: String): String {
    if (accent == "Default") {
        return "    val colors = baseColors"
    }
    return "    val accent = if (isDark) " +
        "RikkaAccentDark.$accent else RikkaAccent.$accent\n" +
        "    val colors = baseColors.withAccent(accent)"
}
